language: c
dist: xenial
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - sourceline: "ppa:team-gcc-arm-embedded/ppa"
    packages:
      - python3
      - gcc-arm-embedded

install:
  - wget -qO - https://raw.githubusercontent.com/JuulLabs-OSS/debian-mynewt/master/mynewt.gpg.key | sudo apt-key add -
  - echo "deb https://raw.githubusercontent.com/JuulLabs-OSS/debian-mynewt/master latest main" > mynewt.list
  - sudo mv mynewt.list /etc/apt/sources.list.d/
  - sudo apt-get update
  - sudo apt install newt

before_script:
  - newt install

script:
  - newt build pca10056_tinyusb
