language: c
dist: xenial
compiler:
  - gcc
  
addons:
  apt:
    sources:
      - sourceline: "ppa:team-gcc-arm-embedded/ppa"
    packages:
      - python3
      - ruby
      - gcc-arm-embedded

install:
  - wget -qO - https://raw.githubusercontent.com/JuulLabs-OSS/debian-mynewt/master/mynewt.gpg.key | sudo apt-key add -
  - sudo echo "deb https://raw.githubusercontent.com/JuulLabs-OSS/debian-mynewt/master latest main" > /etc/apt/sources.list.d/mynewt.list
  - sudo apt-get update
  - sudo apt install newt

script:
  - echo test travis
